"""add telegram bot fields to users

Revision ID: 6ebfcdb89d6a
Revises: e8f3a2b4c9d2
Create Date: 2025-12-09 15:25:41.805535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebfcdb89d6a'
down_revision: Union[str, None] = 'e8f3a2b4c9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('global_channels_tg_id_key', 'global_channels', type_='unique')
    op.drop_constraint('global_channels_username_key', 'global_channels', type_='unique')
    op.drop_index('idx_global_channels_tg_id', table_name='global_channels')
    op.drop_index('idx_global_channels_username', table_name='global_channels')
    op.create_index(op.f('ix_global_channels_tg_id'), 'global_channels', ['tg_id'], unique=True)
    op.create_index(op.f('ix_global_channels_username'), 'global_channels', ['username'], unique=True)
    op.alter_column('leads', 'global_message_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_leads_global_message', table_name='leads')
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('telegram_bot_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('telegram_verification_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('telegram_verification_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_verification_expires')
    op.drop_column('users', 'telegram_verification_code')
    op.drop_column('users', 'telegram_bot_enabled')
    op.drop_column('users', 'telegram_chat_id')
    op.create_index('idx_leads_global_message', 'leads', ['global_message_id'], unique=False)
    op.alter_column('leads', 'global_message_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_global_channels_username'), table_name='global_channels')
    op.drop_index(op.f('ix_global_channels_tg_id'), table_name='global_channels')
    op.create_index('idx_global_channels_username', 'global_channels', ['username'], unique=False)
    op.create_index('idx_global_channels_tg_id', 'global_channels', ['tg_id'], unique=False)
    op.create_unique_constraint('global_channels_username_key', 'global_channels', ['username'])
    op.create_unique_constraint('global_channels_tg_id_key', 'global_channels', ['tg_id'])
    # ### end Alembic commands ###
