"""add notification preferences to users

Revision ID: 90d975fc91dd
Revises: b789adcb0ff3
Create Date: 2025-12-03 14:49:35.833805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d975fc91dd'
down_revision: Union[str, None] = 'b789adcb0ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Получатель уведомления'),
    sa.Column('type', sa.Enum('LEAD_CREATED', 'LEAD_STATUS_CHANGED', 'LEAD_ASSIGNED', 'RULE_TRIGGERED', 'SYSTEM', name='notificationtype'), nullable=False, comment='Тип уведомления'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Заголовок уведомления'),
    sa.Column('message', sa.Text(), nullable=False, comment='Текст уведомления'),
    sa.Column('related_lead_id', sa.UUID(), nullable=True, comment='ID связанного лида (если применимо)'),
    sa.Column('extra_data', sa.Text(), nullable=True, comment='Дополнительные данные в JSON'),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Когда уведомление было прочитано'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_related_lead_id'), 'notifications', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('in_app_notifications_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notify_on_new_lead', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notify_on_lead_status_change', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notify_on_lead_assignment', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_on_lead_assignment')
    op.drop_column('users', 'notify_on_lead_status_change')
    op.drop_column('users', 'notify_on_new_lead')
    op.drop_column('users', 'in_app_notifications_enabled')
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_lead_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
