"""add global channels and subscriptions

Revision ID: c4f2a1d8e9b0
Revises: 5783172b665b
Create Date: 2025-12-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4f2a1d8e9b0'
down_revision: Union[str, None] = '5783172b665b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создать таблицу global_channels
    op.create_table('global_channels',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tg_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('title', sa.String(length=500), nullable=True),
        sa.Column('channel_type', sa.String(length=50), nullable=True),
        sa.Column('last_message_id', sa.BigInteger(), nullable=True),
        sa.Column('last_collected_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tg_id'),
        sa.UniqueConstraint('username')
    )
    op.create_index('idx_global_channels_tg_id', 'global_channels', ['tg_id'], unique=False)
    op.create_index('idx_global_channels_username', 'global_channels', ['username'], unique=False)

    # Создать таблицу global_messages
    op.create_table('global_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('author_tg_id', sa.BigInteger(), nullable=True),
        sa.Column('author_username', sa.String(length=255), nullable=True),
        sa.Column('media_type', sa.String(length=50), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['global_channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('channel_id', 'tg_message_id', name='uq_global_messages_channel_tg_id')
    )
    op.create_index('idx_global_messages_channel', 'global_messages', ['channel_id'], unique=False)
    op.create_index('idx_global_messages_sent_at', 'global_messages', ['sent_at'], unique=False)

    # Создать таблицу channel_subscriptions
    op.create_table('channel_subscriptions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('telegram_account_id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['channel_id'], ['global_channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['telegram_account_id'], ['telegram_accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'channel_id', name='uq_subscription_tenant_channel')
    )
    op.create_index('idx_subscriptions_tenant', 'channel_subscriptions', ['tenant_id'], unique=False)
    op.create_index('idx_subscriptions_channel', 'channel_subscriptions', ['channel_id'], unique=False)

    # Создать таблицу rule_analysis_progress
    op.create_table('rule_analysis_progress',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('rule_id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('last_analyzed_message_id', sa.UUID(), nullable=True),
        sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
        sa.Column('messages_analyzed', sa.Integer(), nullable=False),
        sa.Column('leads_created', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['channel_id'], ['global_channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['last_analyzed_message_id'], ['global_messages.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('rule_id', 'channel_id', name='uq_rule_channel')
    )

    # Добавить global_message_id в таблицу leads (nullable, будет заполнен позже)
    op.add_column('leads', sa.Column('global_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_leads_global_message_id', 'leads', 'global_messages', ['global_message_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_leads_global_message', 'leads', ['global_message_id'], unique=False)

    # Изменить message_id на nullable (будет удален позже)
    op.alter_column('leads', 'message_id', nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Откатить изменения в leads
    op.alter_column('leads', 'message_id', nullable=False)
    op.drop_index('idx_leads_global_message', table_name='leads')
    op.drop_constraint('fk_leads_global_message_id', 'leads', type_='foreignkey')
    op.drop_column('leads', 'global_message_id')

    # Удалить таблицы в обратном порядке
    op.drop_table('rule_analysis_progress')

    op.drop_index('idx_subscriptions_channel', table_name='channel_subscriptions')
    op.drop_index('idx_subscriptions_tenant', table_name='channel_subscriptions')
    op.drop_table('channel_subscriptions')

    op.drop_index('idx_global_messages_sent_at', table_name='global_messages')
    op.drop_index('idx_global_messages_channel', table_name='global_messages')
    op.drop_table('global_messages')

    op.drop_index('idx_global_channels_username', table_name='global_channels')
    op.drop_index('idx_global_channels_tg_id', table_name='global_channels')
    op.drop_table('global_channels')

    # ### end Alembic commands ###
